---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/dparra0007-ib/java-microservices-spring-cloud-config # default
          #username: abc
          #password: abc
          search-paths:
            - 'station*'
          repos:
             local:
                pattern: '*/local'
                uri: https://github.com/dparra0007-ib/java-microservices-spring-cloud-config-local #alt
                search-paths:
                 - 'station*'
          default-label: main
security:
  basic:
    enabled: true
  user:
    name: exam
    password: exam
# logging:
#   level:
#     ROOT: 'DEBUG'